### ISSUE TITLE
When `restartPolicy` is `ExitCode` and a pod is deleted (137), the entire TFJob will still be marked as failed.

### ISSUE THREAD

**Issue by rllin** [kubeflow/common#186]
*Expectations*: if a replica has `restartPolicy=ExitCode`, then a pod deletion (triggers `137`) should cause that pod to restart without triggering TFJob failure.
*Reality*: The entire TFJob fails.

However, the correct behavior happens for `OnFailure` where the pod is properly restarted without the entire job failing.

How to reproduce:
1. Take below spec [0], and apply.
2. Delete the evaluator pod.
3. See that the entire job fails.
4. Replace the evaluator pod's `restartPolicy` with `OnFailure`, repeat steps 1,2 and see that the pod restarts without failing the job.

Suspected issue (may not be core issue):
- Every replica type is checked for [failures](https://github.com/kubeflow/training-operator/blob/master/pkg/controller.v1/tensorflow/tfjob_controller.go#L501)
- Regardless of replica type, if the replica has a failure and if the job is [not restarting](https://github.com/kubeflow/training-operator/blob/master/pkg/controller.v1/tensorflow/tfjob_controller.go#L503-L507), it will be [marked for job failure](https://github.com/kubeflow/training-operator/blob/master/pkg/controller.v1/tensorflow/tfjob_controller.go#L513-L520)
- Seems like that L513 block should also NOT trigger if the jobStatus.Conditions is running?

[0] TFJob spec.

```
apiVersion: kubeflow.org/v1
kind: TFJob
spec:
  tfReplicaSpecs:
    Chief:
      replicas: 1
      restartPolicy: ExitCode
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          affinity: {}
          containers:
          - command: [ "/bin/bash", "-c", "--" ]
            args: [ "while true; do sleep 30; done;" ]
            image: busybox
            imagePullPolicy: Always
            name: tensorflow
            ports:
            - containerPort: 2222
              name: tfjob-port
              protocol: TCP
            resources:
              limits:
                cpu: "2"
                memory: 10Gi
    Evaluator:
      replicas: 1
      restartPolicy: ExitCode
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
          - command: [ "/bin/bash", "-c", "--" ]
            args: [ "while true; do sleep 30; done;" ]
            image: busybox
            imagePullPolicy: Always
            name: tensorflow
            ports:
            - containerPort: 2222
              name: tfjob-port
              protocol: TCP
            resources:
              limits:
                cpu: "2"
                memory: 10Gi
```
