### ISSUE TITLE
prow does not have ability to list repo collaborators

### ISSUE THREAD

**Issue by fejta** [kubeflow/common#3]
/assign @jlewi

```yaml
{
  component:  "hook"   
  error:  "status code 403 not one of [204 404 302], body: {"message":"Must have push access to view repository collaborators.","documentation_url":"https://developer.github.com/v3/repos/collaborators/#check-if-a-user-is-a-collaborator"}"   
  event-GUID:  "ca394c90-559d-11e9-945f-ee71934d44cc"   
  event-type:  "pull_request_review"   
  level:  "error"   
  msg:  "Failed to check if author is a collaborator."   
  org:  "kubeflow"   
  plugin:  "lgtm"   
  pr:  2   
  repo:  "common"   
  review:  221946237   
  reviewer:  "terrytangyuan"   
  url:  "https://github.com/kubeflow/common/pull/2#pullrequestreview-221946237"   
 }
```
