### ISSUE TITLE
Proposal: using gang scheduling API for generic distributed training support in Kubeflow

### ISSUE THREAD

**Issue by karthikv2k** [kubeflow/common#37]
# Problem
Currently in Kubeflow, we have a controller per framework (e.g. TF-Job, and PyTorch-Operator) and to support a new framework, the message we are giving is that users have to write a new controller. This is a lot of friction for data scientists who most likely don’t know Go-Lang and K8s. Even if they do, getting a version of controller deployed in a corp cluster is not easy. 
# Proposed Solution
However, in reality users actually don’t have to write a new controller if they have a generic Gang scheduling API and in fact TF-Job controller exposes a restricted version of the API that works for almost all of the use cases. In fact, the Google AI Platform team implemented distributed [PyTorch](https://aihub.cloud.google.com/u/0/p/products%2F59f96517-9a20-4d4d-916c-ff2d2affda6d) and [XGBoost](https://aihub.cloud.google.com/u/0/p/products%2F067176a1-c5ca-4f7b-bace-37790cc9676a) jobs using TF-Job API for the Google AI-Hub. So if we can create a controller for gang scheduling it will make it easy to add support for new frameworks.
## Advantages
Less effort to support a new framework (users don’t need K8s or Go-Lang expertise)
A better story for portability between Kubeflow and other platforms like Mesos. The same container can be used in other platforms without any changes.
## Other infras that support some version of gang scheduling API
* [Google AI Platform training 
](https://cloud.google.com/ml-engine/docs/distributed-training-containers)
* [Amazon Sagemaker](https://docs.aws.amazon.com/sagemaker/latest/dg/your-algorithms-training-algo.html#your-algorithms-training-algo-running-container-dist-training)
* [Mesos/Uber’s Michelangelo](http://events17.linuxfoundation.org/sites/events/files/slides/MesosCon_Distributed_Deep_Learning_v4.pdf)
* YARN (not natively but with some application logic in Application Master, e.g. [TonY](https://github.com/linkedin/TonY))
## Frameworks Support
From my understanding, distributed training for following frameworks can be implemented easily using just a generic gang scheduling.
* TensorFlow
* Horovod
* PyTorch
* XGBoost
* Julia
* LightGBM
## Rough API Spec
Almost same as current tf-job spec but with more generic names and generalizing #worker groups.
```
apiVersion: kubeflow.org/v1beta1
kind: GangJob
metadata:
  generateName: gangjob
  namespace: kubeflow
spec:
  replicaSpecs:
    WorkerGroup1:
      replicas: 4
      restartPolicy: OnFailure
      template:
        spec:
          containers:
          - name: 
            image: 
            command:
    WorkerGroup2:
      replicas: 3
      restartPolicy: OnFailure
      template:
        spec:
          containers:
          - name: 
            image: 
            Command:
    .
    .
    .
    WorkerGroupN:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
          - name: 
            image: 
            command:
```
